### PR TITLE
Improvement on adblocker

### PR DESCRIPTION
**Pull request by Tropicalista**
Please read here for reference:https://www.kaushik.net/avinash/adblock-tracking-google-analytics-code-metrics-reports/

### CODE REVIEW

**Comment by vpodk** [comment]
This is not necessary.  The `id="ad-container"`, `id="ad"` and `class="banner"` are enough for different AdBlockers to detect and hide or remove this emulated ad banner.  After that it will be removed from the DOM, so no needs to set the `display` and negative `top`.

**Comment by Tropicalista** [comment]
I'm testing this with uBlock and it's not tracking...

**Comment by vpodk** [comment]
The [uBlock](https://github.com/gorhill/uBlock) does not block elements with class name `"Adsense"`.

In your case, this only works because you added this line:
```javascript
node.style.height = '1px';
```

Komito checks the height of the `"ad-container"` element:
```javascript
node.offsetHeight < 5
```

And if this expression is true, it is considered that AdBlocker has cleared the contents of this element.

Please post an issue to add support of [uBlock](https://github.com/gorhill/uBlock).

**Comment by Tropicalista** [comment]
That's why I created the "ins" element that is used by Adsense, probably the most used ad platform.

`var node = dom.appendChild(dom.document.body, dom.createElement('ins'));`

Apart from this do you know how can I test if Komito is correctly tracking adblocks? I don't see anything in the debug...

**Comment by vpodk** [comment]
uBlock filters the `ins` tags only for this case:
`publicdomainq.net##ins.adsbygoogle`

https://github.com/uBlockOrigin/uAssets/blob/master/filters/unbreak.txt#L775

Please post an issue to add support for uBlock and we will implement it a soon as possible.

**Comment by vpodk** [comment]
To enable AdBlockers tracking, you need to enable this feature, because it is disabled by default:

```javascript
'trackAdblock': 0,    // Tracks page views with blocked ads. (Experimental)
```

**Pull request closed without merging**
